// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejsffrbrqgvbxzgmrlcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqc2ZmcmJycWd2Ynh6Z21ybGNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTEwOTIsImV4cCI6MjA2NTQ2NzA5Mn0.Pjy6PumViQTDF-6Zo1Z9upSqBweCxoN_faeBK2w1WV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);